### ISSUE TITLE
does it support moveit ? which launch file?

### ISSUE THREAD

**Issue by mfkenson** [elephantrobotics/mycobot_ros#19]
https://github.com/elephantrobotics/mycobot_moveit

i came across this repo.? which one is more appropriate?

**Comment by zlj-zz** [comment]
I am coding the document now.

**Comment by zlj-zz** [comment]
yes, support moveit

**Comment by mfkenson** [comment]
omg you are rapid. thanks for that.

**Comment by zlj-zz** [comment]
The document has been updated. I will close the issue.
