### ISSUE TITLE
Adding CI for build testing

### ISSUE THREAD

**Issue by Tiryoh** [elephantrobotics/mycobot_ros#21]
How about adding a CI configuration (e.g. https://github.com/ros-industrial/industrial_ci) to check if catkin_make can be done without errors?
I think you'll notice bugs like #20 right away.
I can send a PR if you wish.

**Comment by zlj-zz** [comment]
Of course

**Comment by Tiryoh** [comment]
OK! I'll send a PR.

**Comment by Tiryoh** [comment]
@zlj-zz Which branch should I send the request to?
What is the difference between `noetic`, `master` and `dev`?

**Comment by zlj-zz** [comment]
master

**Comment by Tiryoh** [comment]
> why the env is melodic? It's same with kinetic?

ROS Kinetic and Ubuntu 16.04 has been EOL (End of Life).
It's not exactly the same, but it can be used in much the same way, so I'll check if I can add Kinetic.
It could be difficult because it is not supported officially anymore...

> All features are OK？

I haven't tested all, but it seems OK. I don't have a camera for myCobot.

**Comment by zlj-zz** [comment]
The PR has been merged and the issue will be closed. Notice here.
