### ISSUE TITLE
End-effectors urdf/srdf?

### ISSUE THREAD

**Issue by TrajM** [elephantrobotics/mycobot_ros#29]
Hello, I just started using myCobot with ROS and I want to run an application with the suction pump.
I am new to ROS, so I am not sure if the code is already available here. I wanted to ask if there is a file to define the suction pump model and how to attach it to the robot arm?
Thank you

**Comment by Eheech** [comment]
Sorry, we don't have any files to define the suction pump model at the moment .

**Comment by junjungoal** [comment]
Hi, I would also like you to add an urdf file for an adaptive gripper.
Thank you very much.

**Comment by zlj-zz** [comment]
@TrajM @junjungoal The gripper model has been added to the URDF of pro320 model.

Please check [https://github.com/elephantrobotics/mycobot_ros/tree/main/urdf/320_urdf](https://github.com/elephantrobotics/mycobot_ros/tree/main/urdf/320_urdf).😊

**Comment by junjungoal** [comment]
@zlj-zz 
that's awesome!! 
Thank you very much for handling it promptly.
