### ISSUE TITLE
ImportError: No module named mycobot_description.srv

### ISSUE THREAD

**Issue by weixiaoqiong** [elephantrobotics/mycobot_ros#31]
Traceback (most recent call last):
  File "/home/wwd/catkin_mycobot_ros/src/mycobot_ros/mycobot_280/scripts/listen_real.py", line 9, in <module>
    from mycobot_description.srv import GetAngles
ImportError: No module named mycobot_description.srv

**Comment by zlj-zz** [comment]
Change the `mycobot_description` to `mycobot_communication` is OK.
I have fixed the error.

**Comment by zlj-zz** [comment]
I will close this issue，Too long no reply.
