### ISSUE TITLE
mycobotpi catkin_make error

### ISSUE THREAD

**Issue by yo4hi6o** [elephantrobotics/mycobot_ros#43]
Hi
If you change the ros_catkin_ws originally in mycobotpi and run the catkin_make, the following error occurs. Is there a way to solve this?
```
pi@raspberrypi:~/ros_catkin_ws $ catkin_make
Traceback (most recent call last):
  File "/home/pi/ros_catkin_ws/devel/bin/catkin_make", line 7, in <module>
    with open(python_script, 'r') as fh:
IOError: [Errno 2] No such file or directory: '/home/pi/ros_catkin_ws/src/catkin/bin/catkin_make'

```

**Comment by Eheech** [comment]
What changes did you make to os_catkin_ws ? Maybe you can upload the review process ,  let us check .

**Comment by Eheech** [comment]
If you follow the tutorial in our gitbook , will it return this error ?

**Comment by yo4hi6o** [comment]
I just changed rosrun mycobot_ros slider_control.py from the issue(#36 ) to / dev / ttyAMA0.
Also, the same error occurred in catkin_make when creating a new catkin_ws described in the README of micobotpi.
Currently, I don't have this machine at hand, so I can contact you for details on Monday.

**Comment by Eheech** [comment]
Have you tried ' catkin_init_workspace ' , bafore you used ' catkin_make ' ?

**Comment by yo4hi6o** [comment]
> Have you tried ' catkin_init_workspace ' , bafore you used ' catkin_make ' ?

OK,
I will try it once.

**Comment by Eheech** [comment]
In this tutorial : https://www.elephantrobotics.com/docs/myCobot-en/3-development/4-ros&moveit/2-install_ros_package.html
before  ' **Installation** '  you can use these commands :
![image](https://user-images.githubusercontent.com/48149929/140466772-ef27b0b7-82e3-4fed-9681-276ce7aef90a.png)
and then :
![image](https://user-images.githubusercontent.com/48149929/140466829-c4c9e77d-158c-45a1-8f6d-3c474f24ff8c.png)

**Comment by yo4hi6o** [comment]
OK,
I don't have the actual machine right now, so I will try it at the beginning of the week and report it.
Thank you

**Comment by Eheech** [comment]
You're welcom, hope i can help you .

**Comment by yo4hi6o** [comment]
Hi
A similar error occurs, and after purchase, no changes have been made at the system location. I've done a lot of WS creation in regular ROS and MyCobot, but do I need any special initial setup for MyCobotpi?

```
pi@raspberrypi:~ $ mkdir -p ~/catkin_ws/src
pi@raspberrypi:~ $ cd ~/catkin_ws/src
pi@raspberrypi:~/catkin_ws/src $ catkin_init_workspace
Traceback (most recent call last):
  File "/home/pi/ros_catkin_ws/devel/bin/catkin_init_workspace", line 7, in <module>
    with open(python_script, 'r') as fh:
IOError: [Errno 2] No such file or directory: '/home/pi/ros_catkin_ws/src/catkin/bin/catkin_init_workspace'
pi@raspberrypi:~/catkin_ws/src $ 
```

**Comment by Eheech** [comment]
Have you tired to use ' catkin_init_workspace ' in derectory ' ros_catkin_ws ' ?

**Comment by yo4hi6o** [comment]
Hi,
It is m same in ros_catkin_ws.
thank you
```
pi@raspberrypi:~ $ cd ros_catkin_ws
pi@raspberrypi:~/ros_catkin_ws $ catkin_init_workspace
Traceback (most recent call last):
  File "/home/pi/ros_catkin_ws/devel/bin/catkin_init_workspace", line 7, in <module>
    with open(python_script, 'r') as fh:
IOError: [Errno 2] No such file or directory: '/home/pi/ros_catkin_ws/src/catkin/bin/catkin_init_workspace'
pi@raspberrypi:~/ros_catkin_ws $ 
```

**Comment by Eheech** [comment]
Which Ros do you install in Raspberry ? Noetic or Kinetic ? If you are not sure , you can use command ' roscore ' to check .

**Comment by yo4hi6o** [comment]
It is kinetic that was originally installed.

**Comment by Eheech** [comment]
Would you mind offer a screenshot of your system ?

**Comment by Eheech** [comment]
Please check ~/.bashrc and ~/.zshrc , make sure you have added ros path .

**Comment by yo4hi6o** [comment]
![2021-11-08-154352_1280x720_scrot](https://user-images.githubusercontent.com/74748434/140696028-8f4374d1-1107-4eaf-b20b-a9ece0f97369.png)

**Comment by Eheech** [comment]
Please use these two commands ' cat ~/.bashrc | grep 'ros' ' and ' cat ~/.zshrc '  and send screenshot to us , we wanna find out what the problem it is , thank you very much !!!!

**Comment by yo4hi6o** [comment]
PATH is in .bash.
Why do I get such an error
I'm curious.

![2021-11-08-163412_1280x720_scrot](https://user-images.githubusercontent.com/74748434/140701773-356c5dd9-5aa9-4484-a6ec-a3bda4a13bb2.png)

**Comment by Eheech** [comment]
Please try this way , thank you
![image](https://user-images.githubusercontent.com/48149929/140713607-0bb6c657-e87c-4346-bf74-fc03a56458e5.png)

**Comment by yo4hi6o** [comment]
OK, thank you. For a business trip until the day after tomorrow I will try it the day after tomorrow. thank you!

**Comment by yo4hi6o** [comment]
I was able to resolve the error by changing this path.
Thank you very much.

**Comment by Eheech** [comment]
You're welcome, we're delighted to help you.
